---
name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Create release
        run: |
          cd ./
          npm install
          gulp bundle
          gh release create $GITHUB_RUN_NUMBER 'build/ui-bundle.zip'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
